// Generated by .NET Reflector from C:\inetpub\wwwroot\sc902h\sc902h.local\bin\Sitecore.Kernel.dll
namespace Sitecore.Install
{
    using Sitecore.Common;
    using System;

    internal class PackageInstallationContext : Switcher<bool, PackageInstallationContext>
    {
        public PackageInstallationContext() : base(true)
        {
        }

        public static bool IsActive =>
            Switcher<bool, PackageInstallationContext>.CurrentValue;
    }
}
